"""Initial migration

Revision ID: 0f3d8b6666b6
Revises: 
Create Date: 2024-03-24 07:34:08.998962

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0f3d8b6666b6'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pastes',
    sa.Column('title', sa.String(length=65), nullable=True),
    sa.Column('text_block', sa.Text(), nullable=True),
    sa.Column('destruction_time', postgresql.ENUM('DEFAULT', 'AFTER_READ', 'TEN_MINUTES', 'ONE_HOUR', 'ONE_DAY', 'ONEW_WEEK', name='destructs_enum'), server_default='DEFAULT', nullable=False),
    sa.Column('views', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pastes')
    # ### end Alembic commands ###
